version: '3'

services:
  nodejs:
    volumes:
     - "/home/sandeep/BluetoothProject/BluetoothApp/public:/home/node/bluetoothApp:rw"
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: bluetooth_nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: bluetooth_webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network


  database:
    image: 'mongo'
    container_name: 'bluetooth_mongo'
    ports:
        - '27017:27017'

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

